// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2XWeGnln0QWiFnr_qPdgh87gz7mznm-E',
    appId: '1:183764560118:web:636091ba316ac6343da4d7',
    messagingSenderId: '183764560118',
    projectId: 'corretor-gabaritos-app',
    authDomain: 'corretor-gabaritos-app.firebaseapp.com',
    storageBucket: 'corretor-gabaritos-app.firebasestorage.app',
    measurementId: 'G-KC7RLV64HG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAYRT20mus7S3Be3YeAzc4Dbk_QRqZP6w',
    appId: '1:183764560118:android:114c6e97ae47db863da4d7',
    messagingSenderId: '183764560118',
    projectId: 'corretor-gabaritos-app',
    storageBucket: 'corretor-gabaritos-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxBeNfKtqI4d5rFFwjediMEQVh_GZrZJg',
    appId: '1:183764560118:ios:50a8b2026a6cd9263da4d7',
    messagingSenderId: '183764560118',
    projectId: 'corretor-gabaritos-app',
    storageBucket: 'corretor-gabaritos-app.firebasestorage.app',
    iosBundleId: 'com.example.fluterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxBeNfKtqI4d5rFFwjediMEQVh_GZrZJg',
    appId: '1:183764560118:ios:50a8b2026a6cd9263da4d7',
    messagingSenderId: '183764560118',
    projectId: 'corretor-gabaritos-app',
    storageBucket: 'corretor-gabaritos-app.firebasestorage.app',
    iosBundleId: 'com.example.fluterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2XWeGnln0QWiFnr_qPdgh87gz7mznm-E',
    appId: '1:183764560118:web:8552426fe43daad33da4d7',
    messagingSenderId: '183764560118',
    projectId: 'corretor-gabaritos-app',
    authDomain: 'corretor-gabaritos-app.firebaseapp.com',
    storageBucket: 'corretor-gabaritos-app.firebasestorage.app',
    measurementId: 'G-RTQ8RPC62N',
  );
}
